insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Antonino', 'Cannavacciuolo', '1975-11-09', 'chef1.jpg');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Carlo', 'Cracco', '1965-10-08', 'chef51.jpg');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Iginio', 'Massari', '1946-05-04', 'chef101.jpg');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Alessandro', 'Borghese', '1976-09-19', 'chef151.png');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Joe', 'Bastianich', '1968-09-17', 'chef201.jpg');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Max', 'Mariola', '1975-12-13', 'chef251.jpeg');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Bruno', 'Barbieri', '1962-08-28', 'chef301.jpg');
insert into chef (id, name, surname, date_birth, path_image) values(nextval('chef_seq'), 'Giorgio', 'Locatelli', '1963-10-20', 'chef351.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Massimo', 'Bottura', '1962-09-30', 'chef401.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Niko', 'Romito', '1974-04-30', 'chef451.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Enrico', 'Bartolini', '1979-11-24', 'chef501.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Moreno', 'Cedroni', '1964-07-09', 'chef551.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Heinz', 'Beck', '1963-11-03', 'chef601.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Davide', 'Oldani', '1967-10-01', 'chef651.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Franco', 'Pepe', '1965-05-24', 'chef701.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Cristina', 'Bowerman', '1966-10-10', 'chef751.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Norbert', 'Niederkofler', '1961-09-05', 'chef801.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Gennaro', 'Esposito', '1970-03-31', 'chef851.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Pietro', 'Leemann', '1961-09-20', 'chef901.jpg');
insert into chef (id, name, surname, date_birth, path_image) values (nextval('chef_seq'), 'Mauro', 'Uliassi', '1958-09-10', 'chef951.jpg');


insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Pomodori', 'ingredient1.jpg', 'Deliziosi pomodori freschi, ideali per preparare salse saporite, insalate estive e molti altri piatti mediterranei. Perfetti per dare colore e gusto.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Olio di oliva', 'ingredient51.jpg', 'Olio extravergine di oliva, di qualità superiore, estratto a freddo per preservare tutte le proprietà nutritive e organolettiche. Ottimo per condimenti e cottura.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Aglio', 'ingredient101.jpg', 'Spicchi di aglio aromatico, essenziali per insaporire una vasta gamma di piatti, dalle salse alle carni, fino alle verdure. Un ingrediente fondamentale nella cucina mediterranea.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Basilico', 'ingredient151.jpg', 'Foglie di basilico fresco, dal profumo intenso e aromatico. Ideali per preparare il pesto alla genovese, guarnire pizze, insalate e molte altre pietanze.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Pasta', 'ingredient201.jpg', 'Pasta italiana di alta qualità, trafilata al bronzo e a lenta essiccazione. Disponibile in varie forme, perfetta per esaltare ogni tipo di sugo, dalle ricette tradizionali a quelle più innovative.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Formaggio Parmigiano Reggiano', 'ingredient251.jpg', 'Formaggio stagionato, dal sapore ricco e complesso. Ideale da grattugiare su paste, risotti, zuppe, o da gustare in scaglie con un buon bicchiere di vino.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Mozzarella', 'ingredient301.jpg', 'Formaggio fresco e filante, prodotto con latte vaccino di alta qualità. Ottimo per preparare la pizza, insalate capresi, e molti altri piatti. La sua consistenza morbida e il suo sapore delicato la rendono versatile.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Prosciutto Crudo', 'ingredient351.jpg', 'Prosciutto crudo stagionato, dal sapore dolce e leggermente salato. Perfetto per antipasti, panini gourmet e come accompagnamento per formaggi e frutta. Un’eccellenza della tradizione italiana.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Cipolla', 'ingredient401.jpg', 'Cipolle aromatiche, base perfetta per una vasta gamma di piatti, dalle zuppe alle salse, fino ai soffritti. Essenziali in cucina per aggiungere sapore e dolcezza naturale alle ricette.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Riso Arborio', 'ingredient451.jpg', 'Riso Arborio di alta qualità, con chicchi grandi e perlati. Ideale per preparare risotti cremosi e consistenti, ma anche per timballi e altre specialità della cucina italiana.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Peperoncino', 'ingredient501.jpg', 'Il peperoncino è una spezia piccante che viene usata in molte ricette italiane per aggiungere sapore e calore. È spesso utilizzato intero, macinato o sotto forma di fiocchi.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Pecorino Romano', 'ingredient551.jpg', 'Formaggio stagionato a pasta dura, il Pecorino Romano è prodotto con latte di pecora. Ha un sapore forte e salato ed è spesso grattugiato su paste e zuppe per aggiungere un tocco di sapidità.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Vongole', 'ingredient601.jpg', 'Le vongole sono molluschi bivalvi usati in molti piatti di mare italiani, come gli spaghetti alle vongole. Vengono cotte generalmente in padella con aglio, olio e vino bianco.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Rosmarino', 'ingredient651.jpg', 'Erba aromatica con foglie aghiformi, il rosmarino è molto usato nella cucina italiana per insaporire carni, patate e pane. Il suo aroma è forte e legnoso.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Salvia', 'ingredient701.jpg', 'Erba aromatica con foglie vellutate, la salvia è comune nei piatti di carne e nelle preparazioni a base di burro, come i famosi gnocchi al burro e salvia.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Polpo', 'ingredient751.jpg', 'Il polpo è un mollusco molto apprezzato nella cucina italiana, spesso cotto lentamente per renderlo tenero. Viene usato in insalate di mare, primi piatti e secondi.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Capperi', 'ingredient801.jpg', 'Piccoli boccioli di fiori in salamoia, i capperi aggiungono un sapore salato e acido a molti piatti italiani, come il vitello tonnato e la pasta alla puttanesca.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Rucola', 'ingredient851.jpg', 'La rucola è una verdura a foglia verde dal sapore leggermente piccante. È usata in insalate, pizze e come guarnizione per piatti di carne e pasta.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Lenticchie', 'ingredient901.jpg', 'Legumi piccoli e nutrienti, le lenticchie sono usate in zuppe e stufati italiani, soprattutto nelle regioni del centro e sud Italia, come la famosa zuppa di lenticchie.');
insert into ingredient (id, name, path_image, description) values(nextval('ingredient_seq'), 'Melanzane', 'ingredient951.jpg', 'Ortaggi versatili, le melanzane sono utilizzate in molti piatti italiani, tra cui la parmigiana di melanzane e la caponata. Vengono spesso grigliate, fritte o cotte al forno.');


insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Pizza Margherita', 701, 'Una pizza classica italiana con salsa di pomodoro, mozzarella fresca, e foglie di basilico, cotta nel forno a legna. Creata in onore della Regina Margherita, rappresenta i colori della bandiera italiana.', '1Main.jpg', '1Extra1.jpg', '1Extra2.jpg', '1Extra3.jpg', '_Mescola 500 g di farina, 325 ml di acqua, 10 g di sale, 2 g di lievito di birra e impasta fino a ottenere un composto liscio. Lascia lievitare per 8-24 ore.\nDividi l impasto lievitato in palline, stendi ogni pallina formando un disco.\nSpalma il disco con salsa di pomodoro, aggiungi mozzarella a pezzetti e foglie di basilico.\nInforna a 250°C per circa 10 minuti, fino a doratura.\nAggiungi un filo di olio di oliva a crudo e servi calda.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Spaghetti alla Carbonara', 651, 'Un piatto di pasta cremoso preparato con uova, pecorino romano, guanciale croccante e pepe nero macinato fresco. Originaria del Lazio, è una delle ricette più amate e discusse, con numerose varianti e segreti tramandati.', '51Main.jpg', '51Extra1.jpg', '51Extra2.jpg', '51Extra3.jpg', '_Cuoci 400 g di spaghetti in abbondante acqua salata.\nRosola 150 g di guanciale a cubetti in una padella senza olio fino a renderlo croccante.\nMescola 4 uova con 100 g di pecorino romano grattugiato e pepe nero.\nScola gli spaghetti al dente, trasferiscili nella padella col guanciale, aggiungi la salsa di uova e mescola velocemente.\nAggiungi altro pecorino e pepe nero a piacere e servi subito.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Risotto alla Milanese', 501, 'Un risotto cremoso tipico di Milano, aromatizzato con zafferano e parmigiano reggiano, servito al dente. Simbolo della cucina milanese, spesso accompagnato da ossobuco, rappresenta la tradizione culinaria lombarda.', '101Main.jpg', '101Extra1.jpg', '101Extra2.jpg', '101Extra3.jpg', '_Porta a ebollizione 1,5 l di brodo di carne.\nRosola una cipolla tritata con 80 g di burro, aggiungi 350 g di riso Arborio o Carnaroli.\nSfuma con 100 ml di vino bianco, poi aggiungi brodo poco alla volta mescolando continuamente.\nSciogli una bustina di zafferano in un pò di brodo caldo e aggiungi al risotto a metà cottura.\nA fine cottura, aggiungi 50 g di burro e 50 g di parmigiano grattugiato, mescola e servi caldo.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Ravioli di Ricotta e Spinaci', 751, 'Deliziosi ravioli ripieni di ricotta fresca e spinaci, serviti con salsa di burro e salvia o pomodoro. Piatti tipici delle festività italiane, i ravioli variano di ripieno e salsa a seconda delle regioni.', '151Main.jpg', '151Extra1.jpg', '151Extra2.jpg', '151Extra3.jpg', '_Mescola 250 g di ricotta con 200 g di spinaci lessati e tritati, aggiungi sale, pepe e noce moscata.\nImpasta 400 g di farina con 4 uova, stendi la pasta sottile.\nDistribuisci cucchiaini di ripieno sulla sfoglia, copri con un altra sfoglia e taglia i ravioli.\nCuoci in abbondante acqua salata per pochi minuti, finché vengono a galla.\nScolali e condiscili con burro fuso e salvia.') ;
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Lasagne alla Bolognese', 401, 'Strati di pasta all uovo, ragù alla bolognese e besciamella, cotti al forno fino a ottenere una crosticina dorata. Un piatto iconico della cucina emiliana, noto per la sua ricchezza e complessità di sapori.', '201Main.jpg', '201Extra1.jpg', '201Extra2.jpg', '201Extra3.jpg', '_Rosola cipolla, carota e sedano tritati con olio, aggiungi 500 g di carne macinata, sfuma con vino rosso, aggiungi passata di pomodoro e cuoci a fuoco lento per 2 ore.\nFai una roux con 50 g di burro e 50 g di farina, aggiungi 500 ml di latte, mescola fino a ottenere una salsa densa.\nIn una teglia, alterna strati di pasta per lasagne, ragù, besciamella e parmigiano grattugiato.\nInforna a 180°C per 30-40 minuti.\nLascia riposare qualche minuto prima di servire.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Ossobuco alla Milanese', 801, 'Stinco di vitello tenero brasato con verdure, vino bianco e brodo, servito con gremolata e risotto alla milanese. Questo piatto tradizionale è un omaggio alla cucina milanese, noto per la sua delicatezza e sapore intenso.', '251Extra1.jpg', '251Extra1.jpg', '251Extra2.jpg', '251Extra3.jpg', '_Infarnia leggermente 4 ossibuchi, rosolali in olio e burro.\nAggiungi cipolla, carota e sedano tritati, sfuma con vino bianco.\nAggiungi brodo, passata di pomodoro, sale e pepe, copri e cuoci a fuoco lento per 1,5-2 ore.\nPrepara un trito di aglio, prezzemolo e scorza di limone.\nCospargi gli ossibuchi con la gremolada prima di servire.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Tiramisù', 101, 'Un dessert italiano classico a base di strati di savoiardi imbevuti di caffè e crema di mascarpone, spolverato con cacao amaro. Originario del Veneto, il tiramisù è diventato un simbolo della pasticceria italiana in tutto il mondo.', '301Main.jpg', '301Extra1.jpg', '301Extra2.jpg', '301Extra3.jpg', '_Monta 4 tuorli con 100 g di zucchero, aggiungi 500 g di mascarpone e mescola fino a ottenere una crema liscia.\nMonta a neve 4 albumi e incorporali delicatamente alla crema di mascarpone.\nPrepara 300 ml di caffè e lascialo raffreddare.\nInzuppa i savoiardi nel caffè e disponili in uno strato in una teglia.\nAlterna strati di savoiardi e crema, finisci con uno strato di crema e spolvera con cacao amaro. Lascia riposare in frigo per almeno 4 ore.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Pesto alla Genovese', 351, 'Una salsa saporita fatta con basilico fresco, pinoli, parmigiano, aglio e olio extravergine di oliva, ideale per condire la pasta. Emblema della cucina ligure, il pesto è apprezzato per la sua freschezza e semplicità.', '351Main.jpg', '351Extra1.jpg', '351Extra2.jpg', '351Extra3.jpg', '_Lava e asciuga 50 g di basilico fresco.\nFrulla basilico, 30 g di pinoli, 1 spicchio di aglio e sale grosso.\nAggiungi 50 g di pecorino e 50 g di parmigiano grattugiato.\nAggiungi olio di oliva extravergine a filo mentre frulli fino a ottenere una consistenza cremosa.\nUsa subito o conserva in frigo coperto di olio.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Caprese Salad', 301, 'Una semplice e rinfrescante insalata italiana preparata con pomodori freschi, mozzarella di bufala, basilico e olio di oliva. Nata a Capri, questa insalata è un simbolo dell estate italiana e della cucina mediterranea.', '401Main.jpg', '401Extra1.jpg', '401Extra2.jpg', '401Extra3.jpg', '_Taglia 4 pomodori e 2 mozzarelle di bufala a fette.\nAlterna le fette di pomodoro e mozzarella su un piatto.\nAggiungi foglie di basilico fresco.\nCondisci con olio extravergine di oliva, sale e pepe.\nServi subito, meglio se a temperatura ambiente.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Risotto ai Frutti di Mare', 551, 'Un delizioso risotto ai frutti di mare, preparato con una varietà di pesce fresco e crostacei, cotto alla perfezione. Tipico delle regioni costiere italiane, questo risotto è un piatto estivo perfetto per gli amanti del mare.', '451Main.jpg', '451Extra1.jpg', '451Extra2.jpg', '451Extra3.jpg', '_Prepara un brodo con teste e gusci di gamberi.\nRosola aglio in olio, aggiungi 400 g di frutti di mare (vongole, cozze, gamberi) e sfuma con vino bianco.\nRosola una cipolla tritata, aggiungi 350 g di riso e sfuma con vino bianco.\nAggiungi brodo poco alla volta, mescolando continuamente.\nA metà cottura, aggiungi i frutti di mare, completa la cottura e servi con prezzemolo tritato.');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Spaghetti alle Vongole', 1, 'Piatto tradizionale della cucina napoletana, semplice e delizioso, a base di spaghetti e vongole, con aglio, prezzemolo e un tocco di peperoncino.', '501Main.jpg', '501Extra1.jpg', '501Extra2.jpg', '501Extra3.jpg', '_Lavare bene le vongole e metterle a spurgare in acqua salata per circa un ora.\nIn una padella, scaldare olio di oliva con aglio e peperoncino.\nAggiungere le vongole e coprire finché non si aprono.\nCuocere gli spaghetti in acqua salata e scolarli al dente.\nUnire gli spaghetti alle vongole e mescolare bene.\nServire con prezzemolo tritato e un filo di olio.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Fettuccine Alfredo', 601, 'Un classico piatto romano semplice ma ricco, fatto con fettuccine, burro e parmigiano reggiano.', '551Main.jpg', '551Extra1.jpg', '551Extra2.jpg', '551Extra3.jpg', '_Cuocere le fettuccine in abbondante acqua salata.\nIn una padella, sciogliere il burro a fuoco basso.\nScolare la pasta al dente, conservando un po di acqua di cottura.\nUnire la pasta al burro e mescolare bene.\nAggiungere il parmigiano grattugiato e un po di acqua di cottura.\nMescolare finché non si forma una crema liscia e servire subito.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Ribollita', null, 'Tradizionale zuppa toscana fatta con pane raffermo, cavolo nero, fagioli e verdure miste, ideale per i mesi freddi.', '601Main.jpg', '601Extra1.jpg', '601Extra2.jpg', '601Extra3.jpg', '_Ammollare i fagioli secchi per una notte, poi cuocerli.\nIn una pentola, soffriggere cipolla, carota e sedano tritati.\nAggiungere cavolo nero e verza tagliati a pezzi.\nUnire i fagioli e il loro liquido di cottura.\nAggiungere pane raffermo a pezzi e cuocere finché non si amalgama.\nLasciar riposare e riscaldare prima di servire.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Pollo alla Cacciatora', 451, 'Piatto rustico toscano di pollo cotto in un sugo ricco di pomodoro, olive, capperi, aglio e rosmarino.', '651Main.jpg', '651Extra1.jpg', '651Extra2.jpg', '651Extra3.jpg', '_Rosolare i pezzi di pollo in olio di oliva fino a doratura.\nAggiungere aglio, rosmarino, olive e capperi.\nSfumare con vino bianco e lasciar evaporare.\nAggiungere pomodori pelati e cuocere a fuoco lento.\nAggiustare di sale e pepe.\nCuocere finché il pollo è tenero e servire caldo.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Parmigiana di Melanzane', 851, 'Classico piatto napoletano a base di melanzane fritte, salsa di pomodoro, mozzarella e parmigiano cotto al forno.', '701Main.jpg', '701Extra1.jpg', '701Extra2.jpg', '701Extra3.jpg', '_Tagliare le melanzane a fette, salarle e lasciarle scolare.\nFriggere le fette di melanzana in olio di oliva.\nPreparare una salsa di pomodoro semplice con aglio e basilico.\nDisporre a strati melanzane, salsa, mozzarella e parmigiano in una teglia.\nCuocere in forno a 180°C per circa 30 minuti.\nLasciar intiepidire e servire.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Gnocchi alla Sorrentina', 851, 'Gnocchi di patate conditi con salsa di pomodoro, basilico e mozzarella, poi gratinati in forno.', '751Main.jpg', '751Extra1.jpg', '751Extra2.jpg', '751Extra3.jpg', '_Cuocere le patate, schiacciarle e mescolarle con farina e uovo per fare gli gnocchi.\nCuocere gli gnocchi in acqua bollente salata finché non salgono a galla.\nPreparare una salsa di pomodoro semplice.\nMescolare gli gnocchi con la salsa e metterli in una teglia.\nAggiungere mozzarella a cubetti e parmigiano grattugiato.\nCuocere in forno finché la mozzarella è sciolta e dorata.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Coda alla Vaccinara', 151, 'Tradizionale stufato romano di coda di bue, cotto lentamente con sedano, carota, cipolla e pomodori.', '801Main.jpg', '801Extra1.jpg', '801Extra2.jpg', '801Extra3.jpg', '_Rosolare la coda di bue in olio di oliva fino a doratura.\nAggiungere cipolla, carota e sedano tritati.\nSfumare con vino rosso e lasciar evaporare.\nAggiungere pomodori pelati e cuocere a fuoco lento.\nAggiustare di sale e pepe e continuare la cottura finché la carne è tenera.\nServire con una spolverata di prezzemolo tritato.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Arancini di Riso', 251, 'Sfiziosi snack siciliani fatti con riso, ripieni di ragù, piselli e mozzarella, impanati e fritti.', '851Main.jpg', '851Extra1.jpg', '851Extra2.jpg', '851Extra3.jpg', '_Cuocere il riso in brodo e lasciarlo raffreddare.\nPreparare un ragù di carne con piselli.\nFormare palline di riso e farcirle con il ragù e mozzarella.\nPassare le palline nella farina, poi nell uovo sbattuto e nel pangrattato.\nFriggere gli arancini in olio caldo fino a doratura.\nScolare su carta assorbente e servire caldi.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Pasta e Fagioli', 651, 'Un piatto tradizionale contadino, nutriente e saporito, fatto con pasta, fagioli borlotti e aromi vari.', '901Main.jpg', '901Extra1.jpg', '901Extra2.jpg', '901Extra3.jpg', '_Cuocere i fagioli secchi in abbondante acqua.\nIn una pentola, soffriggere cipolla, carota e sedano tritati.\nAggiungere i fagioli cotti e un po della loro acqua di cottura.\nUnire la pasta e cuocere insieme ai fagioli.\nAggiustare di sale e pepe.\nServire con un filo d olio e pepe nero macinato.\n');
insert into recipe (id, nome, chef_id, description, main_image, extra_image1, extra_image2, extra_image3, procedure) values (nextval('recipe_seq'), 'Cannoli Siciliani', 901, 'Deliziosi dolci siciliani composti da croccanti cialde fritte ripiene di crema di ricotta dolce.', '951Main.jpg', '951Extra1.jpg', '951Extra2.jpg', '951Extra3.jpg','_Preparare l impasto per le cialde e lasciarlo riposare.\nStendere l impasto e ritagliare cerchi.\nAvvolgere i cerchi attorno a cannelli metallici e friggere.\nMescolare la ricotta con zucchero a velo e gocce di cioccolato.\nRiempire le cialde fritte con la crema di ricotta.\nDecorare con zucchero a velo e servire.\n');


insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 1, 1, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 1, 301, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 1, 151, 10, 'foglie');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 1, 51, 2, 'cucchiai');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 51, 551, 50, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 51, 201, 200, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 101, 451, 160, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 101, 251, 40, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 101, 401, 1, 'cipolla');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 151, 251, 30, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 151, 401, 1, 'cipolla');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 201, 1, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 201, 401, 1, 'cipolla');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 201, 251, 40, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 201, 201, 200, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 251, 451, 160, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 251, 401, 1, 'cipolla');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 251, 651, 2, 'rametti');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 351, 151, 50, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 351, 101, 1, 'spicchio');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 351, 251, 30, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 401, 1, 2, 'pomodori');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 401, 301, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 401, 151, 10, 'foglie');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 401, 51, 2, 'cucchiai');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 451, 451, 160, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 451, 751, 100, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 451, 601, 200, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 501, 601, 400, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 501, 101, 2, 'spicchi');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 501, 51, 2, 'cucchiai');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 501, 501, 1, 'Peperoncino');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 501, 201, 200, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 551, 251, 50, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 551, 201, 200, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 601, 901, 100, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 601, 401, 1, 'cipolla');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 651, 401, 1, 'cipolla');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 651, 651, 2, 'rametti');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 651, 801, 1, 'cucchiaio');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 701, 1, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 701, 951, 2, 'melanzane');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 701, 251, 50, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 751, 1, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 751, 301, 200, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 751, 251, 30, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 801, 401, 1, 'cipolla');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 801, 651, 2, 'rametti');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 851, 451, 160, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 851, 301, 100, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 851, 251, 30, 'g');

insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 901, 901, 100, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 901, 201, 100, 'g');
insert into used_ingredient (id, recipe_id, ingredient_id, quantity, measurement) values(nextval('used_ingredient_seq'), 901, 401, 1, 'cipolla');